#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_STORAGE)  += storage

storage: common libsel4utils libutils libsel4 libmuslc libsel4muslcsys \
         libsel4vka libsel4allocman libsel4vspace libsel4simple libsel4simple-default \
         libsel4platsupport libsel4platsupport libcpio libelf \
         libusbdrivers libsel4dma libsel4sync
